---
version: '3.8'

services:
  telegram_bot:
    build: .
    image: telegram_bot:latest
    container_name: telegram-bot
    restart: always
    environment:
      - TELEGRAM_API_TOKEN=your_telegram_api_token
      - CHATGPT_API_KEY=your_chatgpt_api_key
      - GPT_MODEL=gpt-3.5-turbo
      # - ALLOWED_CHAT_IDS=123445566,95848449884
      - CHAT_HISTORY_SIZE=20
      - MAX_TOKENS=500
